services:
  accounts:
    image: "jeanchris/accounts:s4"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jeanchris
  loans:
    image: "jeanchris/loans:s4"
    container_name: loans_ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jeanchris
  cards:
    image: "jeanchris/cards:s4"
    container_name: cards_ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jeanchris
networks:
  jeanchris:
    driver: "bridge"
